apiVersion: v1
kind: Service
metadata:
  name: devops-assessment-service
  namespace: devops-assessment
spec:
  type: NodePort
  selector:
    app: devops-assessment-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
